### ISSUE TITLE
Unable to copy text from edit fields in browser

### ISSUE THREAD

**Issue by CyrilleB79** [nvdaes/clipContentsDesigner#25]
## Describe the bug ##
With this add-on, unable to copy text from an edit field in a browser.

## To Reproduce ##
1. Open a page in Chrome, e.g. this issue.
2. Inn the comment field at the bottom, write something
3. Press Shift+Home to select the just typed text
4. Press control+C
   "Aucune sélection" (French), i.e. "No selection" in English, is reported.
5. Press NVDA+Windows+C
   "Aucun texte à ajouter" and "Impossible d'ajouter" (French), e.g. "No text to add" and "Impossible to add" in English, is heard.
6. Press control+V
   The text copied at steps 4. and 5. is not in the clipboard.

## Expected behavior ##
At step 4., the selected text should be copied to the clipboard.
At step 5., the selected text should be added to the clipboard.

## Screenshots ##
N/A

## System configuration ##
- Product version:
  Clip Contents Designer: 12.0
- Other relevant software or settings: 
  Chrome: Version 87.0.4280.66 (Build officiel) (64 bits)
  Also tested with IE11.

## Additional context ##
I have checked that with this add-on disabled, the issue does not occur.

**Comment by nvdaes** [comment]
Thanks for reporting. I will take care.
