### ISSUE TITLE
Improve documentation of settings panel

### ISSUE THREAD

**Issue by CyrilleB79** [nvdaes/clipContentsDesigner#26]
## Describe the bug ##
I am a new user of this add-on.
The documentation does not allow to know clearly what each option in the setting panel is doing.

## To Reproduce ##

Here is what is not clear or incorrect in the preferences menu paragraph:
* In the "Preferences Menu" paragraph, one bullet for each option in the setting panel would be clearer.
* what is the difference between each display format of the clipboard content shown in browse mode for a user?
* "emulate copy" and "emulate cut": what are they doing with respect to standard copy and cut?
* explain the difference of "clipboard not empty" and clipboard contains text": not all users may think that clipboard may contain a file.
* "preference menu" paragraph name: Now it is a setting panel in the preferences window.

Also a dialog appears at installation regarding emulate copy/paste, but, again, this feature is not clearly defined in the doc. So it is hard to answer. Fortunately, you indcate that it can be changed later...

## Expected behavior ##

Answers to all these questions in the doc.

## Screenshots ##
N/A

## System configuration ##
- Product version:
  Version 12.0
- Other relevant software or settings: 
  N/A

## Additional context ##
I am a brand new user of this add-on.

**Comment by nvdaes** [comment]
Thanks, I'll try to clarify things discussing it with you.
